import assert from "node:assert/strict";
import test from "node:test";

import { buildProofDraft, processAction } from "../netlify/functions/run-marketing-queue.mjs";

const campaign = {
  id: "campaign-native-draft",
  status: "active",
  approved_at: "2026-08-09T18:00:00.000Z",
  approved_by: "owner-1",
  automation_mode: "bounded_auto",
  paid: false,
  channels: ["google_business"],
  start_at: "2026-08-10T00:00:00.000Z",
  end_at: "2026-09-10T00:00:00.000Z",
  blocked_claims: ["free estimate"],
};

const content = {
  id: "content-native-draft",
  campaign_id: campaign.id,
  title: "Door repair",
  service: "Door repair",
  city: "Midvale",
  status: "idea",
  permission_status: "unknown",
  proof_summary: "Repaired a sticking interior door at 123 Main St. Contact: demo@example.com, 385-555-0100. Licensed and guaranteed work.",
  call_to_action: "Request a repair at HomeRepairSLC.com.",
  notes: null,
};

test("native proof drafts redact obvious private data and reject prohibited claims", () => {
  const draft = buildProofDraft(campaign, content);
  assert.match(draft.draft_copy, /Door repair in Midvale/);
  assert.match(draft.draft_copy, /\[address removed\]/);
  assert.match(draft.draft_copy, /\[email removed\]/);
  assert.match(draft.draft_copy, /\[phone removed\]/);
  assert.doesNotMatch(draft.draft_copy, /licensed|guaranteed/i);
  assert.match(draft.draft_copy, /Request a repair at HomeRepairSLC\.com/);
});

test("native draft execution needs an approved envelope but no generator webhook or external request", async () => {
  const action = {
    id: "action-native-draft",
    campaign_id: campaign.id,
    content_id: content.id,
    action_type: "generate_content",
    channel: "google_business",
    scheduled_for: null,
    requires_approval: false,
    approved_at: "2026-08-10T18:00:00.000Z",
    status: "running",
    attempts: 1,
    idempotency_key: "native-draft-v1",
    payload: {},
  };
  const calls = [];
  const originalFetch = global.fetch;
  global.fetch = async (url, options = {}) => {
    const href = String(url);
    calls.push({ href, method: options.method || "GET", body: options.body });
    if (href.includes("/marketing_campaigns?")) return Response.json([campaign]);
    if (href.includes("/marketing_content?")) return Response.json([content]);
    if (href.includes("/settings?")) return Response.json([]);
    if (href.includes("action_type=eq.publish_content")) return Response.json([]);
    if (href.includes("/marketing_content?") && options.method === "PATCH") return Response.json([{ ...content, status: "draft" }]);
    if (href.includes("/marketing_actions?") && options.method === "PATCH") return Response.json([{ ...action, status: "succeeded" }]);
    throw new Error(`Unexpected request: ${href}`);
  };

  try {
    const result = await processAction({
      supabaseUrl: "https://supabase.test",
      serviceRoleKey: "test-key",
      userId: "owner-1",
      paidExecutionMode: "disabled",
      organicExecutionMode: "disabled",
      connectorSecret: "",
      generatorWebhookUrl: "",
      metricsWebhookUrl: "",
      channelWebhookUrls: {},
    }, action);
    assert.deepEqual(result, { id: action.id, status: "succeeded", native_draft: true });
    assert.equal(calls.some(({ href }) => href.includes("connector")), false);
    assert.equal(calls.some(({ href }) => href.includes("/rpc/")), false);
    const contentPatch = calls.find(({ href, method }) => href.includes("/marketing_content?") && method === "PATCH");
    assert.match(contentPatch.body, /Draft generated by action action-native-draft/);
    const actionPatch = calls.find(({ href, method, body }) => href.includes("/marketing_actions?") && method === "PATCH" && String(body).includes("native_proof_draft_v1"));
    assert.ok(actionPatch);
  } finally {
    global.fetch = originalFetch;
  }
});
